[2022-03-15 15:13:49,154] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T15:12:35.288730+00:00 [queued]>
[2022-03-15 15:13:49,162] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T15:12:35.288730+00:00 [queued]>
[2022-03-15 15:13:49,163] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 15:13:49,163] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 15:13:49,163] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 15:13:49,173] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): to_sql> on 2022-03-15 15:12:35.288730+00:00
[2022-03-15 15:13:49,177] {standard_task_runner.py:52} INFO - Started process 27972 to run task
[2022-03-15 15:13:49,183] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'to_sql', 'scheduled__2022-03-15T15:12:35.288730+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp7alzu6bt', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp36cja_8n']
[2022-03-15 15:13:49,186] {standard_task_runner.py:77} INFO - Job 340: Subtask to_sql
[2022-03-15 15:13:49,239] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T15:12:35.288730+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 15:13:49,289] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=to_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T15:12:35.288730+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T15:12:35.288730+00:00
[2022-03-15 15:13:50,115] {logging_mixin.py:109} INFO - Empty DataFrame
Columns: [id, title, servings, summary, diets, equipment, ingredients]
Index: []
[2022-03-15 15:13:50,129] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:50,130] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:50,534] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:50,535] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:51,070] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:51,071] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:51,496] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:51,497] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:51,911] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:51,912] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:52,325] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:52,326] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:52,746] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:52,748] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:53,136] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:53,137] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:53,657] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:53,658] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:54,033] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:54,034] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:54,399] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:54,400] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:54,813] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:54,814] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:55,227] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:55,228] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:55,759] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:55,761] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:56,149] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:56,150] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:56,533] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:56,535] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:56,925] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:56,927] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:57,304] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:57,305] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:57,957] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:57,958] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:58,366] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:13:58,416] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:13:58,847] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 180, in to_sql
    print(pd.concat([pd.DataFrame(columns=columnsrecipe),recipelist], ignore_index=True))
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid
[2022-03-15 15:13:58,864] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=to_sql, execution_date=20220315T151235, start_date=20220315T201349, end_date=20220315T201358
[2022-03-15 15:13:58,880] {standard_task_runner.py:89} ERROR - Failed to execute job 340 for task to_sql
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 180, in to_sql
    print(pd.concat([pd.DataFrame(columns=columnsrecipe),recipelist], ignore_index=True))
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid
[2022-03-15 15:13:58,955] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 15:13:58,976] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
