[2022-03-15 19:19:00,433] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T19:17:48.451776+00:00 [queued]>
[2022-03-15 19:19:00,441] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T19:17:48.451776+00:00 [queued]>
[2022-03-15 19:19:00,441] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 19:19:00,441] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 19:19:00,442] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 19:19:00,451] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): to_sql> on 2022-03-15 19:17:48.451776+00:00
[2022-03-15 19:19:00,457] {standard_task_runner.py:52} INFO - Started process 35045 to run task
[2022-03-15 19:19:00,466] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'to_sql', 'scheduled__2022-03-15T19:17:48.451776+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpygqug5l9', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpwry667wr']
[2022-03-15 19:19:00,475] {standard_task_runner.py:77} INFO - Job 369: Subtask to_sql
[2022-03-15 19:19:00,546] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T19:17:48.451776+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 19:19:00,599] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=to_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T19:17:48.451776+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T19:17:48.451776+00:00
[2022-03-15 19:19:02,388] {logging_mixin.py:109} INFO - Empty DataFrame
Columns: [id, title, servings, summary, diets, equipment, ingredients]
Index: []
[2022-03-15 19:19:02,396] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:02,398] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:02,859] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:02,860] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:03,654] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:03,656] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:04,287] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:04,288] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:04,832] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:04,833] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:05,376] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:05,378] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:05,880] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:05,881] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:06,292] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:06,293] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:06,861] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:06,863] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:07,289] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:07,294] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:07,782] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:07,783] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:08,217] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:08,218] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:08,764] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:08,765] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:09,443] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:09,444] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:09,888] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:09,890] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:10,407] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:10,408] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:11,095] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:11,096] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:19:11,917] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:19:11,919] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:20:04,056] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:20:04,057] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:20:04,611] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 19:20:04,613] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 19:20:05,039] {logging_mixin.py:109} INFO -         id                                              title  ...                                          equipment                                        ingredients
0   635675                                  Boozy Bbq Chicken  ...  [frying pan, paper towels, skewers, bowl, sauc...  [drink, salt and pepper, whole chicken, pepper...
1   637162  Carrot and Cabbage Salad With Coriander+cumin ...  ...                                                NaN  [cabbage, lime juice, spices, fresh cilantro, ...
2   641975                          Easy Ginger Beef Broccoli  ...                            [wok, frying pan, bowl]  [broth, soy sauce, ginger, broccoli, beef, sug...
3   644387                                      Garlicky Kale  ...                                              [pot]                 [vinegar, olive oil, kale, garlic]
4   648320                         Jade Buddha Salmon Tartare  ...                                                NaN                              [vinegar, lime juice]
5   659143  Salmon, Watercress, Fennel and Baby Beetroot S...  ...           [whisk, slotted spoon, frying pan, bowl]  [beet, black pepper, fennel, wine, water, wate...
6   660405     Smoky Black Bean Soup With Sweet Potato & Kale  ...                       [pot, baking sheet, blender]  [broth, onion, salt and pepper, spread, pepper...
7   663985               Turkey and Rice Stuffed Acorn Squash  ...                                 [oven, frying pan]  [vegeta, red pepper, spinach, salt and pepper,...
8   715446                              Slow Cooker Beef Stew  ...                                      [slow cooker]  [cream of mushroom soup, salt and pepper, onio...
9   715543                                 Homemade Guacamole  ...                                                NaN                                                NaN
10  715594             Homemade Garlic and Basil French Fries  ...                                                NaN                                                NaN
11  716268                        African Chicken Peanut Stew  ...                                        [pot, bowl]  [salt and pepper, ginger, sweet potato, potato...
12  716408  Greek-Style Baked Fish: Fresh, Simple, and Del...  ...                                 [oven, baking pan]  [oregano, fresh basil, tomato, salt and pepper...
13  716426  Cauliflower, Brown Rice, and Vegetable Fried Rice  ...                       [frying pan, food processor]  [cauliflower rice, cauliflower florets, butter...
14  729366                                     Plantain Salad  ...                                 [bowl, frying pan]  [plantain, shrimp, vegetable, vegetable oil, p...
15  766453                                 Hummus and Za'atar  ...      [bowl, frying pan, sauce pan, food processor]  [toast, zaatar, vegetable, paprika, salt, seas...
16  769774  Shredded Roast Beef Stuffed Sweet Potatoes (Wh...  ...                                                NaN                                                NaN
17  794349                   Broccoli and Chickpea Rice Salad  ...                          [whisk, frying pan, bowl]                 [broccoli, seasoning, cooking oil]
18  798400  Spicy Black-Eyed Pea Curry with Swiss Chard an...  ...  [frying pan, oven, sauce pan, roasting pan, si...  [chili pepper, lemon juice, shallot, spices, p...

[19 rows x 7 columns]
[2022-03-15 19:25:02,481] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 35045. PIDs of all processes in the group: [35045]
[2022-03-15 19:25:02,482] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 35045
[2022-03-15 19:25:08,786] {taskinstance.py:1027} INFO - Dependencies not met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T19:17:48.451776+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-03-15 19:25:08,786] {taskinstance.py:1027} INFO - Dependencies not met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T19:17:48.451776+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-03-15 19:25:08,786] {local_task_job.py:99} INFO - Task is not able to be run
[2022-03-15 19:28:56,065] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-15 19:28:56,115] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 181, in to_sql
    recipes.to_sql('recipe',conn, if_exists='replace')
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 2872, in to_sql
    sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 717, in to_sql
    pandas_sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1751, in to_sql
    table = self.prep_table(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 860, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1810, in drop_table
    self.get_table(table_name, schema).drop()
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 942, in drop
    bind._run_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1018, in visit_table
    self.connection.execute(DropTable(table))
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-15 19:28:56,152] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=to_sql, execution_date=20220315T191748, start_date=20220316T001900, end_date=20220316T002856
[2022-03-15 19:28:56,176] {standard_task_runner.py:89} ERROR - Failed to execute job 369 for task to_sql
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 181, in to_sql
    recipes.to_sql('recipe',conn, if_exists='replace')
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 2872, in to_sql
    sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 717, in to_sql
    pandas_sql.to_sql(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1751, in to_sql
    table = self.prep_table(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 860, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py", line 1810, in drop_table
    self.get_table(table_name, schema).drop()
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 942, in drop
    bind._run_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1018, in visit_table
    self.connection.execute(DropTable(table))
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/anaconda3/lib/python3.9/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
