[2022-03-15 21:31:01,108] {taskinstance.py:1027} INFO - Dependencies not met for <TaskInstance: simple_dag.s3_sensor scheduled__2022-03-16T02:27:00.066547+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2022-03-16T02:27:00.066547+00:00 but this is after the task's end date 2022-03-15T21:36:00.983995+00:00.
[2022-03-15 21:31:01,108] {taskinstance.py:1027} INFO - Dependencies not met for <TaskInstance: simple_dag.s3_sensor scheduled__2022-03-16T02:27:00.066547+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2022-03-16T02:27:00.066547+00:00 but this is after the task's DAG's end date 2022-03-15T21:36:00.983995+00:00.
[2022-03-15 21:31:01,111] {local_task_job.py:99} INFO - Task is not able to be run
[2022-03-15 21:32:32,403] {taskinstance.py:1027} INFO - Dependencies not met for <TaskInstance: simple_dag.s3_sensor scheduled__2022-03-16T02:27:00.066547+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2022-03-16T02:27:00.066547+00:00 but this is after the task's end date 2022-03-15T21:37:32.254828+00:00.
[2022-03-15 21:32:32,403] {taskinstance.py:1027} INFO - Dependencies not met for <TaskInstance: simple_dag.s3_sensor scheduled__2022-03-16T02:27:00.066547+00:00 [queued]>, dependency 'Execution Date' FAILED: The execution date is 2022-03-16T02:27:00.066547+00:00 but this is after the task's DAG's end date 2022-03-15T21:37:32.254828+00:00.
[2022-03-15 21:32:32,404] {local_task_job.py:99} INFO - Task is not able to be run
