[2022-03-15 15:00:18,319] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T14:59:00.898134+00:00 [queued]>
[2022-03-15 15:00:18,326] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T14:59:00.898134+00:00 [queued]>
[2022-03-15 15:00:18,326] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 15:00:18,326] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 15:00:18,326] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 15:00:18,335] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): to_sql> on 2022-03-15 14:59:00.898134+00:00
[2022-03-15 15:00:18,340] {standard_task_runner.py:52} INFO - Started process 27593 to run task
[2022-03-15 15:00:18,359] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'to_sql', 'scheduled__2022-03-15T14:59:00.898134+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpyvtjrei5', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpgi6t1625']
[2022-03-15 15:00:18,362] {standard_task_runner.py:77} INFO - Job 334: Subtask to_sql
[2022-03-15 15:00:18,419] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T14:59:00.898134+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 15:00:18,472] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=to_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T14:59:00.898134+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T14:59:00.898134+00:00
[2022-03-15 15:00:19,294] {logging_mixin.py:109} INFO - Empty DataFrame
Columns: [id, title, servings, summary, diets, ingredients, equipment]
Index: []
[2022-03-15 15:00:19,306] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:19,308] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:19,747] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:19,748] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:20,278] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:20,280] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:20,707] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:20,708] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:21,311] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:21,312] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:21,713] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:21,714] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:22,090] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:22,091] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:22,486] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:22,487] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:23,015] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:23,016] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:23,396] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:23,398] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:23,794] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:23,795] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:24,180] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:24,181] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:25,867] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:25,869] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:26,385] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:26,386] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:26,816] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:26,817] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:27,197] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:27,198] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:27,737] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:27,739] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:28,124] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:28,125] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:28,647] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:28,648] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:29,036] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 15:00:29,037] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 15:00:29,750] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 181, in to_sql
    print(pd.concat([recipesql,recipelist]))
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid
[2022-03-15 15:00:29,774] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=to_sql, execution_date=20220315T145900, start_date=20220315T200018, end_date=20220315T200029
[2022-03-15 15:00:29,793] {standard_task_runner.py:89} ERROR - Failed to execute job 334 for task to_sql
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 181, in to_sql
    print(pd.concat([recipesql,recipelist]))
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid
[2022-03-15 15:00:29,864] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 15:00:29,889] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
