[2022-03-15 10:59:10,950] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T10:56:00+00:00 [queued]>
[2022-03-15 10:59:10,958] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T10:56:00+00:00 [queued]>
[2022-03-15 10:59:10,958] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:59:10,958] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 10:59:10,958] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:59:10,966] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): get_recipes> on 2022-03-15 10:56:00+00:00
[2022-03-15 10:59:10,970] {standard_task_runner.py:52} INFO - Started process 19992 to run task
[2022-03-15 10:59:10,977] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'get_recipes', 'scheduled__2022-03-15T10:56:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpj_lstuez', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpxp022pcx']
[2022-03-15 10:59:10,980] {standard_task_runner.py:77} INFO - Job 279: Subtask get_recipes
[2022-03-15 10:59:11,037] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T10:56:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 10:59:11,091] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=get_recipes
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:56:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T10:56:00+00:00
[2022-03-15 10:59:11,107] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 10:59:11,109] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 10:59:11,495] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 10:59:11,496] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 10:59:11,897] {logging_mixin.py:109} INFO - {'pantry': {'excludeIngredients': ['potato'], 'includeIngredients': ['fish'], 'intolerances': 'soy'}, 'user': {'address': '0496 Page Mountains Apt. 722\nHernandezfort, IN 04526', 'description': 'Often focus air race affect. Statement go shoulder believe pretty activity turn. Four face arrive table.', 'name': 'Janet Clements'}}
[2022-03-15 10:59:12,350] {logging_mixin.py:109} INFO -    vegetarian  vegan  glutenFree  dairyFree  ...                                              diets  occasions                               analyzedInstructions                               spoonacularSourceUrl
0       False  False        True      False  ...                         [gluten free, pescatarian]         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/greek-style-baked-fish...
1       False  False        True      False  ...                 [gluten free, primal, pescatarian]         []  [{'name': '', 'steps': [{'number': 1, 'step': ...      https://spoonacular.com/plantain-salad-729366
2       False  False        True       True  ...  [gluten free, dairy free, paleolithic, primal,...         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/jade-buddha-salmon-tar...
3       False  False        True       True  ...             [gluten free, dairy free, pescatarian]         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/balsamic-honey-glazed-...
4       False  False        True       True  ...  [gluten free, dairy free, paleolithic, primal,...         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/salmon-watercress-fenn...
5       False  False        True      False  ...                         [gluten free, pescatarian]         []                                                 []  https://spoonacular.com/filet-mignon-soft-taco...
6       False  False        True       True  ...  [gluten free, dairy free, paleolithic, primal,...         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/cilantro-lime-halibut-...
7       False  False        True      False  ...                         [gluten free, pescatarian]         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/corn-crusted-fish-taco...
8       False  False        True       True  ...             [gluten free, dairy free, pescatarian]         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/salmon-quinoa-risotto-...
9       False  False        True       True  ...             [gluten free, dairy free, pescatarian]         []  [{'name': '', 'steps': [{'number': 1, 'step': ...  https://spoonacular.com/rice-and-peas-with-coc...

[10 rows x 32 columns]
[2022-03-15 10:59:12,386] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,388] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,390] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,392] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,394] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,396] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,398] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,399] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,401] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,403] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,404] {logging_mixin.py:109} INFO - got an unexpected keyword argument 'filename'
[2022-03-15 10:59:12,408] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 10:59:12,409] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 10:59:12,970] {logging_mixin.py:109} INFO - {'pantry': {'excludeIngredients': ['lime'], 'includeIngredients': ['brown rice'], 'intolerances': 'grain'}, 'user': {'address': '07227 Barbara Vista\nStevenbury, MD 07127', 'description': 'Chair them way agency. A drug cell choice rest trip. Inside recently face mind fish up north set.\nCulture arrive else imagine approach say just. Stand door up accept low.', 'name': 'Kimberly Johnson'}}
[2022-03-15 10:59:13,263] {logging_mixin.py:109} INFO - Empty DataFrame
Columns: []
Index: []
[2022-03-15 10:59:13,265] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 108, in get_recipes
    dfrecipe = pd.concat([dfrecipe, getRecipe(response.json()['results'])], ignore_index=True)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 24, in getRecipe
    recipeout = recipelist[['title','servings','summary','diets']]
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['title', 'servings', 'summary', 'diets'], dtype='object')] are in the [columns]"
[2022-03-15 10:59:13,279] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=get_recipes, execution_date=20220315T105600, start_date=20220315T155910, end_date=20220315T155913
[2022-03-15 10:59:13,291] {standard_task_runner.py:89} ERROR - Failed to execute job 279 for task get_recipes
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 108, in get_recipes
    dfrecipe = pd.concat([dfrecipe, getRecipe(response.json()['results'])], ignore_index=True)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 24, in getRecipe
    recipeout = recipelist[['title','servings','summary','diets']]
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['title', 'servings', 'summary', 'diets'], dtype='object')] are in the [columns]"
[2022-03-15 10:59:13,311] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 10:59:13,332] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
